services:
    llamacpp-server:
        image: ghcr.io/ggml-org/llama.cpp:server
        #build:
            #context: llama-cpp/docker
            #dockerfile: Dockerfile
        container_name: llamacpp-server
        environment:
            - HF_TOKEN=${HUGFACE_TOKEN}
            - LLAMA_CACHE=/models/.cache
            - LLAMA_ARG_HF_REPO=${HUGFACE_REPO:-ggml-org/Qwen2.5-Coder-7B-Q8_0-GGUF}
            - LLAMA_ARG_HF_FILE=${HUGFACE_FILE:-qwen2.5-coder-7b-q8_0.gguf}
            - LLAMA_ARG_CTX_SIZE=${CONTEXT_SIZE:-0}
            - LLAMA_ARG_LOG_VERBOSITY=${LOG_LEVEL:-3}

        volumes:
          - llamacpp_volume:/models

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: open-webui
        restart: always
        ports:
            - "127.0.0.1:3388:8080"
        environment:
            - ENABLE_OLLAMA_API=false
            - OPENAI_API_BASE_URL=http://llamacpp-server:8080/v1
            - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
        volumes:
            - webui_volume:/app/backend/data
        depends_on:
            - llamacpp-server

volumes:
  llamacpp_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './llama-cpp/models'

  webui_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './open-webui/data'